export const province = [
  { key: 1, value: "Thành phố Cần Thơ", text: "Thành phố Cần Thơ" },
  { key: 2, value: "Thành phố Đà Nẵng", text: "Thành phố Đà Nẵng" },
  { key: 3, value: "Thành phố Hà Nội", text: "Thành phố Hà Nội" },
  { key: 4, value: "Thành phố Hải Phòng", text: "Thành phố Hải Phòng" },
  { key: 5, value: "Thành phố Hồ Chí Minh", text: "Thành phố Hồ Chí Minh" },
  { key: 6, value: "Tỉnh An Giang", text: "Tỉnh An Giang" },
  { key: 7, value: "Tỉnh Bà Rịa-Vũng Tàu", text: "Tỉnh Bà Rịa-Vũng Tàu" },
  { key: 8, value: "Tỉnh Bắc Giang", text: "Tỉnh Bắc Giang" },
  { key: 9, value: "Tỉnh Bắc Kạn", text: "Tỉnh Bắc Kạn" },
  { key: 10, value: "Tỉnh Bạc Liêu", text: "Tỉnh Bạc Liêu" },
  { key: 11, value: "Tỉnh Bắc Ninh", text: "Tỉnh Bắc Ninh" },
  { key: 12, value: "Tỉnh Bến Tre", text: "Tỉnh Bến Tre" },
  { key: 13, value: "Tỉnh Bình Định", text: "Tỉnh Bình Định" },
  { key: 14, value: "Tỉnh Bình Dương", text: "Tỉnh Bình Dương" },
  { key: 15, value: "Tỉnh Bình Phước", text: "Tỉnh Bình Phước" },
  { key: 16, value: "Tỉnh Bình Thuận", text: "Tỉnh Bình Thuận" },
  { key: 17, value: "Tỉnh Cà Mau", text: "Tỉnh Cà Mau" },
  { key: 18, value: "Tỉnh Cao Bằng", text: "Tỉnh Cao Bằng" },
  { key: 19, value: "Tỉnh Đắk Lắk", text: "Tỉnh Đắk Lắk" },
  { key: 20, value: "Tỉnh Đắk Nông", text: "Tỉnh Đắk Nông" },
  { key: 21, value: "Tỉnh Điện Biên", text: "Tỉnh Điện Biên" },
  { key: 22, value: "Tỉnh Đồng Nai", text: "Tỉnh Đồng Nai" },
  { key: 23, value: "Tỉnh Đồng Tháp", text: "Tỉnh Đồng Tháp" },
  { key: 24, value: "Tỉnh Gia Lai", text: "Tỉnh Gia Lai" },
  { key: 25, value: "Tỉnh Hà Giang", text: "Tỉnh Hà Giang" },
  { key: 26, value: "Tỉnh Hà Nam", text: "Tỉnh Hà Nam" },
  { key: 27, value: "Tỉnh Hà Tĩnh", text: "Tỉnh Hà Tĩnh" },
  { key: 28, value: "Tỉnh Hải Dương", text: "Tỉnh Hải Dương" },
  { key: 29, value: "Tỉnh Hậu Giang", text: "Tỉnh Hậu Giang" },
  { key: 30, value: "Tỉnh Hòa Bình", text: "Tỉnh Hòa Bình" },
  { key: 31, value: "Tỉnh Hưng Yên", text: "Tỉnh Hưng Yên" },
  { key: 32, value: "Tỉnh Khánh Hòa", text: "Tỉnh Khánh Hòa" },
  { key: 33, value: "Tỉnh Kiên Giang", text: "Tỉnh Kiên Giang" },
  { key: 34, value: "Tỉnh Kon Tum", text: "Tỉnh Kon Tum" },
  { key: 35, value: "Tỉnh Lai Châu", text: "Tỉnh Lai Châu" },
  { key: 36, value: "Tỉnh Lâm Đồng", text: "Tỉnh Lâm Đồng" },
  { key: 37, value: "Tỉnh Lạng Sơn", text: "Tỉnh Lạng Sơn" },
  { key: 38, value: "Tỉnh Lào Cai", text: "Tỉnh Lào Cai" },
  { key: 39, value: "Tỉnh Long An", text: "Tỉnh Long An" },
  { key: 40, value: "Tỉnh Nam Định", text: "Tỉnh Nam Định" },
  { key: 41, value: "Tỉnh Nghệ An", text: "Tỉnh Nghệ An" },
  { key: 42, value: "Tỉnh Ninh Bình", text: "Tỉnh Ninh Bình" },
  { key: 43, value: "Tỉnh Ninh Thuận", text: "Tỉnh Ninh Thuận" },
  { key: 44, value: "Tỉnh Phú Thọ", text: "Tỉnh Phú Thọ" },
  { key: 45, value: "Tỉnh Phú Yên", text: "Tỉnh Phú Yên" },
  { key: 46, value: "Tỉnh Quảng Bình", text: "Tỉnh Quảng Bình" },
  { key: 47, value: "Tỉnh Quảng Nam", text: "Tỉnh Quảng Nam" },
  { key: 48, value: "Tỉnh Quảng Ngãi", text: "Tỉnh Quảng Ngãi" },
  { key: 49, value: "Tỉnh Quảng Ninh", text: "Tỉnh Quảng Ninh" },
  { key: 50, value: "Tỉnh Quảng Trị", text: "Tỉnh Quảng Trị" },
  { key: 51, value: "Tỉnh Sóc Trăng", text: "Tỉnh Sóc Trăng" },
  { key: 52, value: "Tỉnh Sơn La", text: "Tỉnh Sơn La" },
  { key: 53, value: "Tỉnh Tây Ninh", text: "Tỉnh Tây Ninh" },
  { key: 54, value: "Tỉnh Thái Bình", text: "Tỉnh Thái Bình" },
  { key: 55, value: "Tỉnh Thái Nguyên", text: "Tỉnh Thái Nguyên" },
  { key: 56, value: "Tỉnh Thanh Hóa", text: "Tỉnh Thanh Hóa" },
  { key: 57, value: "Tỉnh Thừa Thiên Huế", text: "Tỉnh Thừa Thiên Huế" },
  { key: 58, value: "Tỉnh Tiền Giang", text: "Tỉnh Tiền Giang" },
  { key: 59, value: "Tỉnh Trà Vinh", text: "Tỉnh Trà Vinh" },
  { key: 60, value: "Tỉnh Tuyên Quang", text: "Tỉnh Tuyên Quang" },
  { key: 61, value: "Tỉnh Vĩnh Long", text: "Tỉnh Vĩnh Long" },
  { key: 62, value: "Tỉnh Vĩnh Phúc", text: "Tỉnh Vĩnh Phúc" },
  { key: 63, value: "Tỉnh Yên Bái", text: "TTỉnh Yên Bái" },
];
